vich_uploader:
    db_driver: orm

    mappings:
        img_products:
            uri_prefix: /images/products
            upload_destination: '%kernel.project_dir%/public/images/products'
            namer:
                service: Vich\UploaderBundle\Naming\PropertyNamer
                options: { property: 'slug' }

        img_pj_products:
            uri_prefix: /images/products
            upload_destination: '%kernel.project_dir%/public/images/products'
            namer:
                service: Vich\UploaderBundle\Naming\UniqidNamer
